# word/record_word.py

PAGE_TITLE = "ガット登録"
NO_USER_ERROR = "ユーザー情報がありません"
UNSELECTED_OPTION = "未選択"
RACKET_LABEL = "ラケット"
VERTICAL_LABEL = "縦ストリング"
HORIZONTAL_LABEL = "横ストリング"
SET_DATE_LABEL = "張った日"
BREAK_DATE_LABEL = "切れた日"
TENSION_LABEL = "テンション"
COST_LABEL = "金額"
MEMO_LABEL = "打感メモ"
RATING_LABEL = "打感評価"
REGISTER_BUTTON_LABEL = "登録する"
REGISTER_SUCCESS_MSG = "登録完了"
RACKET_REQUIRED_ERROR = "ラケットは必須です"
VERTICAL_REQUIRED_ERROR = "縦ストリングは必須です"
HORIZONTAL_REQUIRED_ERROR = "横ストリングは必須です"